In [3]:
%pylab
import numpy as np
import cv2
import matplotlib.pyplot as plt
from IPython.display import IFrame, display

# !pip install opencv-python

Using matplotlib backend: QtAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


ModuleNotFoundError: No module named 'cv2'

In [2]:
image = cv2.imread('Figures/paisaje.jpg')
cv2.imshow('ImagenOriginal',image)
image.shape

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

(520, 900, 3)

In [3]:
# Reescalar la imagen

Nx, Ny = 512,512
image = cv2.resize(image,(Nx,Ny))

# Escala de grises

image_gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

print(image_gray.shape)

# Conversion a punto flotante para hacer math
image_gray_float = np.float64(image_gray)

(512, 512)


In [4]:
cv2.imshow('ImageGray', image_gray)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [5]:
# Vover al esquema RGB para ver cada capa
image1 = cv2.cvtColor(image_gray, cv2.COLOR_GRAY2RGB)

rojo = image1.copy()

rojo[:,:,0] = 0
rojo[:,:,1] = 0

cv2.imshow('rojo', rojo)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [6]:
verde = image1.copy()

verde[:,:,0] = 0
verde[:,:,2] = 0

cv2.imshow('verde', verde)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [7]:
azul = image1.copy()

azul[:,:,1] = 0
azul[:,:,2] = 0

cv2.imshow('azul', azul)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [8]:
# Obtener FFT

FFT = np.fft.fft2(image_gray_float)

FFT = np.fft.fftshift(FFT) # Centrar las frecuencias en 0

FFTA = np.abs(FFT)

#print(FFTA[0])

FFTLog = np.log10(FFTA)

#print(FFTLog[0])



In [9]:
#plt.hist2d(FFTLog[0], FFTLog[2])

In [10]:
cv2.imshow('EspectroFourier', np.uint8(255*FFTLog/np.max(FFTLog)))

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [11]:
# Diseñemos nuestro filtro

F1 = np.arange( -0.5*Nx+1, 0.5*Nx+1, 1)
F2 = np.arange( -0.5*Ny+1, 0.5*Ny+1, 1)
[X,Y] = np.meshgrid(F1,F2)

D = np.sqrt(X**2+Y**2)
D = D/np.max(D)
print(D)

[[0.99609375 0.99414254 0.99219519 ... 0.99414254 0.99609375 0.99804879]
 [0.99414254 0.9921875  0.9902363  ... 0.9921875  0.99414254 0.99610141]
 [0.99219519 0.9902363  0.98828125 ... 0.9902363  0.99219519 0.99415789]
 ...
 [0.99414254 0.9921875  0.9902363  ... 0.9921875  0.99414254 0.99610141]
 [0.99609375 0.99414254 0.99219519 ... 0.99414254 0.99609375 0.99804879]
 [0.99804879 0.99610141 0.99415789 ... 0.99610141 0.99804879 1.        ]]


In [12]:
# Definamos un radio de corte

D0 = 0.
D02 = 0.2

Huv = np.zeros((Nx,Ny))

# Filtro de bajas frecuencias

for i in range(Nx):
    for j in range(Ny):
        if(D[i,j] > D0):
            Huv[i,j] = 0.
        if(D[i,j] < D02):
            Huv[i,j] = 1.

In [13]:
cv2.imshow('FiltroDeBaja', np.uint8(255*Huv))

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [14]:
# Usar el teorema de convolucion

Guv = Huv*FFT

# Tomar la magnitud

GuvA = np.abs(Guv)

# Escalamos

GuvA = np.uint8( 255*GuvA/np.max(GuvA) )

In [15]:
cv2.imshow('EspectroConFiltro', np.uint8(255*GuvA))

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [16]:
# Ahora tomemos la transformada inversa

Gxy = np.fft.ifft2(Guv)
Gxy = np.abs(Gxy)

print(Gxy)

[[245.05726739 245.07595362 244.87628759 ... 243.61961283 244.07552304
  244.6725    ]
 [252.23956187 252.10282079 251.70260932 ... 250.70441279 251.26350871
  251.90969659]
 [258.61805705 258.22574742 257.51172958 ... 257.19553933 257.82359826
  258.43954503]
 ...
 [241.52000086 241.37171695 241.08370465 ... 241.75553901 241.67232722
  241.59965784]
 [239.72535987 239.62246973 239.32804791 ... 239.32020018 239.43797868
  239.62683316]
 [240.40558954 240.41316953 240.21965628 ... 239.37213277 239.67777393
  240.11333192]]


In [17]:
cv2.imshow('ImagenConFiltro', np.uint8(Gxy))

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

# References

https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch04.html

# Bordes.

Lugares de la imagen donde hay un cambio brusco de la intensidad.

$$ dI(x,y) = \sqrt{ \bigg(\frac{dI(x,y)}{dx}\bigg)^{2} + \bigg(\frac{dI(x,y)}{dx}\bigg)^{2} }  $$

In [18]:
kernel1 = np.array([-0.5,0,0.5])
kernel2 = np.array([[-0.5],[0],[0.5]]) 

In [19]:
X = cv2.filter2D(image, -1, kernel1)
Y = cv2.filter2D(image, -1, kernel2)

In [20]:
Mxy = np.sqrt(X**2 + Y**2)

# Normalizacion a 1

Mxy = Mxy/np.max(Mxy)

#count = 0
#for i in range(len(Mxy[:,0])):
#    for j in range(len(Mxy[0,:])):
#        if(Mxy[i,j].all() > 0.8):
#            count += 1
            
print(Mxy[5,:])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# Aplicar el filtro y retorna blanco si se cumple condicion

mask = np.where(Mxy > 0.5, 255, 0)

mask = np.uint8(mask)
cv2.imshow('Bordes', mask)



QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to target thread (0x55783b845530)

QObject::moveToThread: Current thread (0x55783b845530) is not the object's thread (0x55783ba5ec20).
Cannot move to tar

In [ ]:
video = cv2.VideoCapture(0)

run = True

while run:
    
    # lectura de imagenes
    ret, frame1 = video.read()
    frame = cv2.cvtColor(frame1, cv2.COLOR_RGB2GRAY)
    
    frame_float = frame.astype(float)
    
    kernel1 = np.array([-0.05,0,0.05])
    kernel2 = np.array([[-0.05],[0],[0.05]]) 
    
    X = cv2.filter2D(frame_float, -1, kernel1)
    Y = cv2.filter2D(frame_float, -1, kernel2)
    
    Mxy = np.sqrt(X**2+Y**2)
    
    # Normalización a 1

    Mxy = Mxy/np.max(Mxy)
    
    mask = np.where(Mxy > 0.05, 255, 0)
    mask = np.uint8(mask)
    
    cv2.imshow('Bordes', mask)
    
    k = cv2.waitKey(1)&0xFF
    if(k == ord('p')):
        
        print('Exit')
        run = False
        break
        
video.release()
cv2.destroyAllWindows()